language: c

compiler:
  - clang
  - gcc

env:
  - GTK_VERSION=3
  - GTK_VERSION=2

before_install:
  - export LIBGTK=$([ "${GTK_VERSION}" == 3 ] && echo 'libgtk-3-dev' || echo 'libgtk2.0-dev')
  - export LIBVTE=$([ "${GTK_VERSION}" == 3 ] && echo 'libvte-2.90-dev' || echo 'libvte-dev')
  - sudo apt-get update -qq

install:
  - sudo apt-get -qq install ${LIBGTK} ${LIBVTE}

before_script:
  - ./autogen.sh

script:
  - ./configure $([ "${GTK_VERSION}" == 3 ] && echo '--enable-gtk3')
  - make
